apiVersion: batch/v1
kind: Job
metadata:
  name: data-loader
  labels:
    prerequisite: model-load
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: inference-checkpoint
        image: us-docker.pkg.dev/cloud-tpu-images/inference/inference-checkpoint:v0.2.2
