# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../gcsfuse

patches:
  - path: deployment.patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
