apiVersion: apps/v1
kind: Deployment
metadata:
  name: '*'
spec:
  template:
    spec:
      nodeSelector:
        eks.amazonaws.com/instance-family: inf2
        eks.amazonaws.com/compute-type: auto
      tolerations:
        - key: aws.amazon.com/neuron
          operator: Exists
          effect: NoSchedule
      containers:
        - name: inference-server
          resources:
            requests:
              aws.amazon.com/neuron: 1
            limits:
              aws.amazon.com/neuron: 1
