apiVersion: v1
kind: Service
metadata:
  name: llm-service
spec:
  selector:
    app: vllm-server
    deployment: vllm-deployment-blueprint
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
