apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: multihost-base
spec:
  leaderWorkerTemplate:
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          app: multihost-inference-server
          examples.ai.gke.io/source: blueprints
      spec:
        containers:
          - name: multihost-leader-base
    workerTemplate:
      metadata:
        labels:
          app: multihost-inference-server
          examples.ai.gke.io/source: blueprints
      spec:
        containers:
          - name: multihost-worker-base