# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: b200.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: TENSOR_PARALLEL_SIZE
          value: "2"
    target:
      kind: Deployment
