apiVersion: apps/v1
kind: Deployment
metadata:
  name: '*'
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.azure.com/accelerator: nvidia
      containers:
      - name: inference-server
        # resources:
        #   requests:
        #     nvidia.com/gpu: 1
        #   limits:
        #     nvidia.com/gpu: 1
