apiVersion: apps/v1
kind: Job
metadata:
  name: '*'
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-tpu-topology: 2x4
        cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
      containers:
      - name: inference-checkpoint
        resources:
          requests:
            google.com/tpu: 8
          limits:
            google.com/tpu: 8