apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: kserve-huggingfaceserver
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: "8080"
  containers:
    - args:
        - --model_name={{.Name}}
      image: kserve/huggingfaceserver:v0.13.0
      name: kserve-container
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
  protocolVersions:
    - v2
    - v1
  supportedModelFormats:
    - autoSelect: true
      name: huggingface
      priority: 1
      version: "1"