apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: kserve-mlserver
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: "8080"
  containers:
    - env:
        - name: MLSERVER_MODEL_IMPLEMENTATION
          value: '{{.Labels.modelClass}}'
        - name: MLSERVER_HTTP_PORT
          value: "8080"
        - name: MLSERVER_GRPC_PORT
          value: "9000"
        - name: MODELS_DIR
          value: /mnt/models
      image: docker.io/seldonio/mlserver:1.3.2
      name: kserve-container
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
  protocolVersions:
    - v2
  supportedModelFormats:
    - autoSelect: true
      name: sklearn
      priority: 2
      version: "0"
    - autoSelect: true
      name: sklearn
      priority: 2
      version: "1"
    - autoSelect: true
      name: xgboost
      priority: 2
      version: "1"
    - autoSelect: true
      name: lightgbm
      priority: 2
      version: "3"
    - autoSelect: true
      name: mlflow
      priority: 1
      version: "1"