apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

components:
  - ../../../components/aws/resources/neuron/1-Inf2
  - ../../../components/storage/vllm/aws/s3

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --max-model-len=2048
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --no-enable-prefix-caching
    target:
      group: apps
      version: v1
      kind: Deployment
  - path: deployment.patch.yaml
    target:
      kind: Deployment
