apiVersion: apps/v1
kind: Deployment
metadata:
  name: '*'
spec:
  template:
    spec:
      nodeSelector:
        eks.amazonaws.com/compute-type: auto
      containers:
      - name: inference-server
        resources:
          requests:
            nvidia.com/gpu: 4
          limits:
            nvidia.com/gpu: 4
